### PR TITLE
Bittrex trading tab

### PR DESCRIPTION
**Pull request by gjhiggins**
Integrated as a discreet menu item (as opposed to a space-consuming permanent tab). Bittrex trading functionality is untested.

### CODE REVIEW

**Comment by StakeBox** [comment]
Thanks for this. I have been crazy busy lately, I will sit down and look this over tonight and try it out.

**Comment by gjhiggins** [comment]
There's no rush. I realise, a bit belatedly, that I didn't exhaustively cross-reference all the returned structure/contents.

**Comment by StakeBox** [comment]
Finally giving this and #5 a proper testing. This seems to be a much better fit. There are errors about the market being invalid, but I think fixing this PR is more desirable than #5, although it would be nice to see the sending BTC via autosell function that is included in #5 brought into the PR, maybe this one could be merged once fixed and there could be another PR for that feature.

**Comment by StakeBox** [comment]
This has now been merged, thanks.

**Pull request merged**
